# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{noda}
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["takuya"]
  s.date = %q{2011-06-03}
  s.description = %q{noda is job queue system using druby }
  s.email = %q{takuya.1st@gmail}
  s.executables = ["noda_job_worker", "noda_job_server"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/noda_job_server",
    "bin/noda_job_worker",
    "lib/noda.rb",
    "lib/noda/job_monitor.rb",
    "lib/noda/job_server.rb",
    "lib/noda/job_worker.rb",
    "lib/noda/rqueue.rb",
    "lib/noda/table.rb",
    "lib/noda/table_auto_saver.rb",
    "lib/noda/task.rb",
    "noda.gemspec",
    "test/test_helper.rb",
    "test/test_job_monitor.rb",
    "test/test_job_server.rb",
    "test/test_job_worker.rb",
    "test/test_noda.rb",
    "test/test_rqueue.rb",
    "test/test_table.rb",
    "test/test_table_saver_woker.rb",
    "test/test_task.rb"
  ]
  s.homepage = %q{http://github.com/takuya/noda}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{noda is job queue system}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

